# ERT Cyborg

- type: entity
  id: StunBatonBorg
  parent: Stunbaton
  name: Recharging Cyborg Baton
  suffix: Cyborg
  components:
  - type: BatterySelfRecharger
    autoRecharge: true
    autoRechargeRate: 20
  - type: Battery # 3/4 the charge capacity but slowly recharges
    maxCharge: 750
    startingCharge: 750
