## Navy Roles

# Navy Officer

- type: job
  id: NavyOfficer
  name: job-name-navy-officer
  description: job-description-navy-officer
  playTimeTracker: JobNavyOfficer
  setPreference: false
  startingGear: NavyOfficerGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-commander
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: NavyOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNavyGold
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHatBeretEliteNavyOfficer
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesHeavyGoldenTrim
    back: ClothingBackpackSatchelLeather
    outerClothing: ClothingOuterArmourInvisible
    neck: ExecutiveIDCard
    id: NavyOfficerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSheathFilledNavyOfficer
    pocket1: BoxFolderCentCom
  storage:
    back:
    - Flash
    - WeaponPulsePistol

# Navy Captain

- type: job
  id: NavyCaptain
  name: job-name-navy-captain
  description: job-description-navy-captain
  playTimeTracker: JobNavyCaptain
  setPreference: false
  startingGear: NavyCaptainGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-null
  canBeAntag: false
  requirements:
  - !type:AgeRequirement
    requiredAge: 21
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: NavyCaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNavyGold
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHatBeretNavyCaptain
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesHeavyGoldenTrim
    back: ClothingBackpackSatchelLeather
    outerClothing: ClothingOuterArmourInvisible
    neck: ExecutiveIDCard
    id: NavyCaptainPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSheathFilledNavyOfficer
    pocket1: BoxFolderCentCom
  storage:
    back:
    - WeaponPulsePistol
    - Flash

# Undercover Officer

- type: job
  id: NavyOfficerUndercover
  name: job-name-navy-officer-undercover
  description: job-description-navy-officer-undercover
  playTimeTracker: JobNavyOfficerUndercover
  setPreference: false
  startingGear: NavyOfficerUndercoverGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-commander
  canBeAntag: false
  requirements:
  - !type:AgeRequirement
    requiredAge: 21
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: NavyOfficerUndercoverGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChameleon
    shoes: ClothingShoesChameleon
    head: ClothingHeadHatChameleon
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsChameleon
    mask: ClothingMaskGasVoiceChameleon
    back: ClothingBackpackChameleon
    outerClothing: ClothingOuterArmourInvisibleChameleon
    neck: ClothingNeckChameleon
    id: ChameleonPDA
    ears: ClothingHeadsetChameleon
    pocket1: WeaponPistolCentcommAgent
  storage:
    back:
    - ExecutiveIDCardChameleon
    - WeaponPulsePistol
    - MagazinePistolNeurotoxin
    - MagazinePistolNeurotoxin
    - Flash

# Special Operations Officer

- type: job
  id: SpecialOperationsOfficer
  name: job-name-special-operations-officer
  description: job-description-operations-officer
  playTimeTracker: JobSpecialOperationsOfficer
  setPreference: false
  startingGear: SpecialOperationsOfficerGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-commander
  canBeAntag: false
  requirements:
  - !type:AgeRequirement
    requiredAge: 21
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: SpecialOperationsOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSpecOps
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHatBeretSecurity
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackSatchelLeather
    outerClothing: ClothingOuterArmourInvisible
    neck: ExecutiveIDCard
    id: SpecialOperationsOfficerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSheathFilledNavyOfficer
    suitstorage: WeaponRifleLecter
    pocket1: WeaponRevolverMateba
  storage:
    back:
    - WeaponPulsePistol
    - HandheldFaxOfficial
    - BoxFolderNuclearCodes # ka-BOOM
    - MagazineRifleUranium
    - MagazineRifleUranium
    - Flash

# Diplomat

- type: job
  id: Diplomat
  name: job-name-diplomat
  description: job-description-diplomat
  playTimeTracker: JobDiplomat
  setPreference: false
  startingGear: DiplomatGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-commander
  canBeAntag: false
  requirements:
  - !type:AgeRequirement
    requiredAge: 21
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: DiplomatGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDiplomat
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesHeavyGoldenTrim
    back: ClothingBackpackSatchelLeather
    outerClothing: ClothingOuterArmourInvisible
    neck: ExecutiveIDCard
    id: DiplomatPDA
    ears: ClothingHeadsetAltCentCom
  storage:
    back:
    - WeaponPulsePistol
    - Flash
