- type: job
  id: DeathSquad
  name: job-name-deathsquad
  description: job-description-deathsquad
  playTimeTracker: JobDeathSquad
  setPreference: false
  startingGear: DeathSquadGear
  icon: "JobIconDeathsquad" #imp
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm, DeathAcidifierImplanter, CentcommFreedomImplanter, RadioImplantCentcomm ]
  requirements: #imp edit
  - !type:OverallPlaytimeRequirement
    time: 4h

- type: startingGear
  id: DeathSquadGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingBackpackDeathSquad
    mask: ClothingMaskGasDeathSquad
    neck: ExecutiveIDCard
    eyes: ClothingEyesGlassesDeathsquad
    ears: ClothingHeadsetDeathsquad
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitDeathsquad
    shoes: ClothingShoesBootsMagDeathsquad
    id: DeathsquadPDA
    pocket1: PhoronSabre
    pocket2: WeaponRevolverMatebaAP
    belt: ClothingBeltDeathsquadWebbingFilled # Centcomm Doesn't use syndicate tech.
  storage:
    back:
    - SpeedLoaderMagnumAP
    - SpeedLoaderMagnumAP
    - ToolDebug # spanish army knife
    - WelderExperimental
    - AmnestizineHypospray
  inhand:
  - WeaponPulseRifle

- type: chameleonOutfit
  id: DeathSquadChameleonOutfit
  job: DeathSquad
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitDeathsquad
    neck: ClothingNeckBronzeheart
