- type: gameMapPool
  id: DefaultMapPoolDevil
  maps:
  - Uoui
  #- PackedDevil
  - ReachDevil
  - WaystationDevil
  #- SalternDevil
  #- MooseDevil
  #- SplitDevil
  #- GlacierDevil
  - LunaDevil
  - PathwayDevil
  - WhisperDevil
  - BananaDevil
  - LilboatDevil
  - HashDevil